/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main documentation sidebar (auto-generated from docs folder)
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // Connie End User Documentation Sidebars
  endUserCBOAdmins: [
    {
      type: 'category',
      label: 'Connie End User - CBO Admins',
      collapsed: false,
      items: [
        'end-users/cbo-admins/getting-started',
        {
          type: 'autogenerated',
          dirName: 'end-users/cbo-admins/voice',
        },
        // Future channel categories will be added here:
        // messaging, socials, fax, email
      ],
    },
  ],

  endUserSupervisors: [
    {
      type: 'category',
      label: 'Connie End User - Supervisors',
      collapsed: false,
      items: [
        'end-users/supervisors/overview',
        // Add more supervisor pages here as they're created
      ],
    },
  ],

  endUserStaffAgents: [
    {
      type: 'category',
      label: 'Connie End User - Staff Agents',
      collapsed: false,
      items: [
        'end-users/staff-agents/overview',
        // Add more staff agent pages here as they're created
      ],
    },
  ],

  endUserTestTeams: [
    {
      type: 'category',
      label: 'Connie End User - Test Teams',
      collapsed: false,
      items: [
        'end-users/test-teams/overview',
        // Add more test teams pages here as they're created
      ],
    },
  ],

  // Connie TechOps Documentation Sidebar (Internal)
  techops: [
    {
      type: 'html',
      value: '<div style="margin: 32px 0 16px 0; padding: 12px; background: linear-gradient(to right, #f5f5f5, transparent); border-left: 3px solid #666;"><span style="font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 1px; font-weight: 600;">⚙️ Internal Only</span></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: '⚙️ Connie TechOps',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'techops/overview',
      },
      items: [
        {
          type: 'category',
          label: 'Account Provisioning',
          collapsed: true,
          items: [
            'techops/account-provisioning/flex-auth0-sso',
            {
              type: 'autogenerated',
              dirName: 'techops/account-provisioning/authentication',
            },
          ],
        },
        {
          type: 'category',
          label: 'Feature Deployment',
          collapsed: true,
          items: [
            'techops/feature-deployment/template-installation',
            'techops/feature-deployment/running-locally',
            'techops/feature-deployment/feature-selection',
            'techops/feature-deployment/voice-voicemail-setup',
            {
              type: 'autogenerated',
              dirName: 'techops/feature-deployment/feature-management',
            },
          ],
        },
        {
          type: 'category',
          label: 'Codebase Reference',
          collapsed: true,
          items: [
            'techops/codebase/template-architecture',
            'techops/codebase/frontend-overview',
            'techops/codebase/backend-overview',
            'techops/codebase/debugging',
            'techops/codebase/updating-documentation',
            {
              type: 'autogenerated',
              dirName: 'techops/codebase/deployment',
            },
            {
              type: 'autogenerated',
              dirName: 'techops/codebase/flex-hooks',
            },
            {
              type: 'autogenerated',
              dirName: 'techops/codebase/template-utilities',
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'techops/troubleshooting',
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
